### ISSUE TITLE
Morrocan Crisis

### ISSUE THREAD

**Issue by EruptedMaster** [Eagle020/ww1#27]

**Comment by martha91** [comment]
https://drive.google.com/file/d/1McUBcMzD_mz2tEJ2xopnnz7K2vqnf4bE/view?usp=sharing

**Comment by EruptedMaster** [comment]
looks good martha

**Comment by martha91** [comment]
update: upper half of flowchart almost done

**Comment by martha91** [comment]
progress report: >30 individual events and  >1k lines of code already written on the agadir chain; >150 lines of flavor text
event chaining and war triggers done
next steps: code in ai behavior, add opinion modifiers, set up troop spawns and territory transfers
